name: Flux
options:
  bundleIdPrefix: com.flux
  deploymentTarget:
    macOS: "15.0"
  createIntermediateGroups: true
  postGenCommand: echo "Project regenerated"

targets:
  Flux:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "**/.gitkeep"
      - path: Sources/Resources
        type: folder
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSHighResolutionCapable: true
        LSApplicationCategoryType: public.app-category.utilities
    settings:
      base:
        PRODUCT_NAME: Flux
        PRODUCT_BUNDLE_IDENTIFIER: com.flux.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_ALLOWED: false
